//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30109.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emtf.Resources.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DebugLogger {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugLogger() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emtf.Resources.Logging.DebugLogger", typeof(DebugLogger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMTF: .
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} was aborted (execution time {2:N0} ms)..
        /// </summary>
        internal static string TestCompleted_Aborted {
            get {
                return ResourceManager.GetString("TestCompleted_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} threw a {2} (execution time {3:N0} ms). {4}.
        /// </summary>
        internal static string TestCompleted_Exception {
            get {
                return ResourceManager.GetString("TestCompleted_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} failed (execution time {2:N0} ms): {3}.
        /// </summary>
        internal static string TestCompleted_Failed {
            get {
                return ResourceManager.GetString("TestCompleted_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} passed (execution time {2:N0} ms)..
        /// </summary>
        internal static string TestCompleted_Passed {
            get {
                return ResourceManager.GetString("TestCompleted_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result unknown..
        /// </summary>
        internal static string TestCompleted_UnknownTestResult {
            get {
                return ResourceManager.GetString("TestCompleted_UnknownTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test log - {1}.
        /// </summary>
        internal static string TestCompleted_UserLogLine {
            get {
                return ResourceManager.GetString("TestCompleted_UserLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        internal static string TestCompleted_UserMessage {
            get {
                return ResourceManager.GetString("TestCompleted_UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test run completed. No tests were executed..
        /// </summary>
        internal static string TestRunCompleted_NoTests {
            get {
                return ResourceManager.GetString("TestRunCompleted_NoTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Test run completed execution of {2:N0} tests in {3:N0} seconds.{0}{1}{4:N0} tests passed ({5:P1}), {6:N0} tests failed ({7:P1}).{0}{1}{8:N0} tests where skipped ({9:P1}), {10:N0} tests where aborted ({11:P1}) and {12:N0} tests threw an exception ({13:P1})..
        /// </summary>
        internal static string TestRunCompleted_TestRunSummary {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestRunSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test run started..
        /// </summary>
        internal static string TestRunStarted {
            get {
                return ResourceManager.GetString("TestRunStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} skipped because the constructor threw a {2}. {3}.
        /// </summary>
        internal static string TestSkipped_ConstructorThrew {
            get {
                return ResourceManager.GetString("TestSkipped_ConstructorThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} skipped because the method is not supported..
        /// </summary>
        internal static string TestSkipped_MethodNotSupported {
            get {
                return ResourceManager.GetString("TestSkipped_MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} skipped because the SkipTest attribute is defined. {2}.
        /// </summary>
        internal static string TestSkipped_SkipTestAttribute {
            get {
                return ResourceManager.GetString("TestSkipped_SkipTestAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} skipped because the PreTestAction or PostTestAction attribute is defined..
        /// </summary>
        internal static string TestSkipped_TestActionAttribute {
            get {
                return ResourceManager.GetString("TestSkipped_TestActionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} skipped because its type is not supported..
        /// </summary>
        internal static string TestSkipped_TypeNotSupported {
            get {
                return ResourceManager.GetString("TestSkipped_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test skip reason unknown..
        /// </summary>
        internal static string TestSkipped_UnknownSkipReason {
            get {
                return ResourceManager.GetString("TestSkipped_UnknownSkipReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test {1} started..
        /// </summary>
        internal static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
    }
}
