//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30109.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emtf.Resources.Logging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StreamLogger {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StreamLogger() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emtf.Resources.Logging.StreamLogger", typeof(StreamLogger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORTED: {0} ({1:N0} ms).
        /// </summary>
        internal static string TestCompleted_Aborted {
            get {
                return ResourceManager.GetString("TestCompleted_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          {0}.
        /// </summary>
        internal static string TestCompleted_AdditionalMessage {
            get {
                return ResourceManager.GetString("TestCompleted_AdditionalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED:  {0} ({1:N0} ms) {2}.
        /// </summary>
        internal static string TestCompleted_Failed {
            get {
                return ResourceManager.GetString("TestCompleted_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED:  {0} ({1:N0} ms).
        /// </summary>
        internal static string TestCompleted_Passed {
            get {
                return ResourceManager.GetString("TestCompleted_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THREW:   {0} in {1} ({2:N0} ms).
        /// </summary>
        internal static string TestCompleted_Throwing {
            get {
                return ResourceManager.GetString("TestCompleted_Throwing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result unknown..
        /// </summary>
        internal static string TestCompleted_UnknownTestResult {
            get {
                return ResourceManager.GetString("TestCompleted_UnknownTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Log  - {0}.
        /// </summary>
        internal static string TestCompleted_UserLogLine {
            get {
                return ResourceManager.GetString("TestCompleted_UserLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run completed (no tests were executed).
        /// </summary>
        internal static string TestRunCompleted_NoTests {
            get {
                return ResourceManager.GetString("TestRunCompleted_NoTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N0.
        /// </summary>
        internal static string TestRunCompleted_TestCountFormatString {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestCountFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run completed execution of {0:N0} tests in {1:N0} seconds..
        /// </summary>
        internal static string TestRunCompleted_TestRunCompleted {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestRunCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0,-14}} {{1,{0:G}:N0}} ({{2:P1}}).
        /// </summary>
        internal static string TestRunCompleted_TestRunResultFormatTemplate {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestRunResultFormatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests aborted:.
        /// </summary>
        internal static string TestRunCompleted_TestsAborted {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestsAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests failed:.
        /// </summary>
        internal static string TestRunCompleted_TestsFailed {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests passed:.
        /// </summary>
        internal static string TestRunCompleted_TestsPassed {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests skipped:.
        /// </summary>
        internal static string TestRunCompleted_TestsSkipped {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestsSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests threw:.
        /// </summary>
        internal static string TestRunCompleted_TestsThrowing {
            get {
                return ResourceManager.GetString("TestRunCompleted_TestsThrowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run containing {0:N0} tests started at {1} on {2}{3}{3}.
        /// </summary>
        internal static string TestRunStarted__Desktop {
            get {
                return ResourceManager.GetString("TestRunStarted__Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run containing {0:N0} tests started at {1}{2}{2}.
        /// </summary>
        internal static string TestRunStarted__Silverlight {
            get {
                return ResourceManager.GetString("TestRunStarted__Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIPPED: Instantiation for {0} threw {1}{2}.
        /// </summary>
        internal static string TestSkipped_ConstructorThrewException {
            get {
                return ResourceManager.GetString("TestSkipped_ConstructorThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          {0}{1}.
        /// </summary>
        internal static string TestSkipped_Message {
            get {
                return ResourceManager.GetString("TestSkipped_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIPPED: Test method {0} not supported{1}.
        /// </summary>
        internal static string TestSkipped_MethodNotSupported {
            get {
                return ResourceManager.GetString("TestSkipped_MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIPPED: SkipTestAttribute defined on {0}{1}.
        /// </summary>
        internal static string TestSkipped_SkipTestAttribute {
            get {
                return ResourceManager.GetString("TestSkipped_SkipTestAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIPPED: PreTestAction or PostTestAction attribute defined on {0}{1}.
        /// </summary>
        internal static string TestSkipped_TestActionAttribute {
            get {
                return ResourceManager.GetString("TestSkipped_TestActionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKIPPED: Type containing {0} not supported{1}.
        /// </summary>
        internal static string TestSkipped_TypeNotSupported {
            get {
                return ResourceManager.GetString("TestSkipped_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test skip reason unknown..
        /// </summary>
        internal static string TestSkipped_UnknownSkipReason {
            get {
                return ResourceManager.GetString("TestSkipped_UnknownSkipReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START:   {0} at {1}{2}.
        /// </summary>
        internal static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
    }
}
