//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30109.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emtf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestRunCompletedEventArgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestRunCompletedEventArgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emtf.Resources.TestRunCompletedEventArgs", typeof(TestRunCompletedEventArgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time must not be greater than the end time..
        /// </summary>
        internal static string ctor_InvalidStartTime {
            get {
                return ResourceManager.GetString("ctor_InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of aborted tests must be greater than or equal to zero..
        /// </summary>
        internal static string ctor_TestsAbortedNegative {
            get {
                return ResourceManager.GetString("ctor_TestsAbortedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of failed tests must be greater than or equal to zero..
        /// </summary>
        internal static string ctor_TestsFailedNegative {
            get {
                return ResourceManager.GetString("ctor_TestsFailedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of passed tests must be greater than or equal to zero..
        /// </summary>
        internal static string ctor_TestsPassedNegative {
            get {
                return ResourceManager.GetString("ctor_TestsPassedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of skipped tests must be greater than or equal to zero..
        /// </summary>
        internal static string ctor_TestsSkippedNegative {
            get {
                return ResourceManager.GetString("ctor_TestsSkippedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of tests that threw an exception must be greater than or equal to zero..
        /// </summary>
        internal static string ctor_TestsThrowingNegative {
            get {
                return ResourceManager.GetString("ctor_TestsThrowingNegative", resourceCulture);
            }
        }
    }
}
